[app_node]
app-node ansible_host=4.193.141.181 private_ip=10.0.1.10

[monitoring_node]
monitoring-node ansible_host=20.205.153.210 private_ip=10.0.1.20

[all:vars]
ansible_user=azureuser
ansible_ssh_private_key_file=../devops-project.pem
ansible_python_interpreter=/usr/bin/python3
vnet_cidr=10.0.0.0/16
